// Single source of truth for the church calendar. Feeds three things from
// one place: the interactive calendar's data file
// (public/js/calendar-events.js, generated by scripts/build.mjs), the
// noscript fallback list on calendar.html ({{EVENTS_NOSCRIPT}}), and the
// Event structured data on calendar.html.

// Special services, concerts and one-off events. Deliberately empty for now
// — no real one-off events could be sourced for this build (see
// services.html for the "confirm with the parish" note). Add real entries
// here as they're announced; recurring weekly worship goes in
// RECURRING_SERIES below instead.
export const ONE_OFF_EVENTS = [
  // { date: '2026-12-24', time: '23:30', title: 'Midnight Mass', location: 'St Martin of Tours' },
];

// Recurring weekly services, sourced from the Bromley community directory's
// listing for this church. The directory also lists an 11am service on
// alternating Sundays (1st/3rd Sung Eucharist, 2nd/4th a different service)
// — that alternation isn't something this simple weekly-recurrence engine
// can express, so it's described in prose on services.html instead of
// listed here; adding it to the calendar grid would need a genuinely
// biweekly rule, not a new row.
//
// To carry a series into next year, just extend `until`. To skip a
// particular date (Christmas, a funeral using the slot, etc.), add it to
// `except`.
export const RECURRING_SERIES = [
  { title: 'Holy Communion', location: 'St Martin of Tours', weekday: 7, time: '08:00', from: '2026-09-13', until: '2027-09-12' },
  { title: 'Family Service', location: 'St Martin of Tours', weekday: 7, time: '09:45', from: '2026-09-13', until: '2027-09-12' },
  { title: 'Evensong', location: 'St Martin of Tours', weekday: 7, time: '18:30', from: '2026-09-13', until: '2027-09-12' },
  { title: 'Holy Communion', location: 'St Martin of Tours', weekday: 3, time: '09:30', from: '2026-09-16', until: '2027-09-15' },
];

const CHURCH_LOCALITY = { addressLocality: 'Chelsfield', addressRegion: 'Kent', addressCountry: 'GB' };

export function placeFor(location) {
  if (!location) return { '@type': 'Place', name: 'St Martin of Tours, Chelsfield' };
  if (location.toLowerCase().includes('martin')) {
    return {
      '@type': 'Place',
      name: location,
      address: { '@type': 'PostalAddress', streetAddress: 'Church Road', postalCode: 'BR6 7SN', ...CHURCH_LOCALITY },
    };
  }
  return { '@type': 'Place', name: location };
}

function pad(n) { return n < 10 ? '0' + n : '' + n; }
function dateStr(d) { return d.getFullYear() + '-' + pad(d.getMonth() + 1) + '-' + pad(d.getDate()); }

function expandSeries(series) {
  const out = [];
  const fromParts = series.from.split('-').map(Number);
  const untilParts = series.until.split('-').map(Number);
  const d = new Date(fromParts[0], fromParts[1] - 1, fromParts[2]);
  const until = new Date(untilParts[0], untilParts[1] - 1, untilParts[2]);
  // JS Date#getDay(): 0 = Sunday ... 6 = Saturday. Convert our ISO weekday
  // (1 = Monday ... 7 = Sunday) to that scale.
  const jsWeekday = series.weekday % 7;
  while (d.getDay() !== jsWeekday) d.setDate(d.getDate() + 1);
  const except = series.except || [];
  while (d <= until) {
    const ds = dateStr(d);
    if (!except.includes(ds)) {
      out.push({ date: ds, time: series.time, title: series.title, location: series.location });
    }
    d.setDate(d.getDate() + 7);
  }
  return out;
}

export function expandEvents() {
  const recurring = RECURRING_SERIES.flatMap(expandSeries);
  return [...ONE_OFF_EVENTS, ...recurring].sort((a, b) =>
    a.date === b.date ? a.time.localeCompare(b.time) : a.date.localeCompare(b.date));
}

export function formatTime12h(time24) {
  const [h, m] = time24.split(':').map(Number);
  const period = h < 12 ? 'am' : 'pm';
  const h12 = h % 12 === 0 ? 12 : h % 12;
  return `${h12}:${pad(m)}${period}`;
}

const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

export function formatEventDate(dateStr) {
  const [y, m, d] = dateStr.split('-').map(Number);
  const date = new Date(y, m - 1, d);
  return `${DAY_NAMES[date.getDay()]} ${d} ${MONTH_NAMES[m - 1]}`;
}
