// Single source of truth for the main nav, the footer's shorter "Explore"
// list, and each page's <head> metadata. Edit this file (and
// src/pages/*.html for content) — public/*.html is generated by
// scripts/build.mjs and should not be hand-edited.
//
// SITEWIDE NOINDEX: every page below sets robots: 'noindex, nofollow'.
// This build was put together from public directory listings, not commissioned
// or reviewed by the parish that runs the real stmartinchelsfield.org.uk —
// see CLAUDE.md's "About this build" section. Keeping every page out of
// search results avoids this prototype ever competing with, or being
// mistaken for, that real site. Remove robots from a page here (see
// kington-parishes' own history of doing exactly this on its go-live day)
// only once the parish has reviewed this build and approved it going live.

// The header's primary nav. "Home" isn't a link here: the brand link in the
// header already goes to index.html.
export const NAV = [
  { href: 'about.html', label: 'History' },
  { href: 'visit-us.html', label: 'Visit Us' },
  { href: 'services.html', label: 'Services' },
  { href: 'calendar.html', label: 'Calendar' },
  { href: 'get-involved.html', label: 'Groups &amp; Activities' },
  { href: 'newsletter.html', label: 'Newsletter' },
  { href: 'people.html', label: 'Clergy &amp; Contacts' },
  { href: 'contact.html', label: 'Contact' },
];

// The footer's shorter "Explore" list — deliberately a different set than
// NAV (includes Safeguarding, which isn't in the primary nav).
export const FOOTER_NAV = [
  { href: 'about.html', label: 'History' },
  { href: 'services.html', label: 'Services' },
  { href: 'get-involved.html', label: 'Groups &amp; Activities' },
  { href: 'safeguarding.html', label: 'Safeguarding' },
  { href: 'privacy-policy.html', label: 'Privacy Policy' },
];

export const PAGES = [
  {
    slug: 'index',
    title: 'St Martin of Tours, Chelsfield — Church of England',
    description: 'St Martin of Tours, Chelsfield: a medieval parish church in the Diocese of Rochester. Service times, how to find us, and how to get involved.',
    active: 'index.html',
    header: true,
    robots: 'noindex, nofollow',
    structuredData: {
      '@context': 'https://schema.org',
      '@type': 'Church',
      name: 'St Martin of Tours, Chelsfield',
      url: 'https://www.stmartinchelsfield.org.uk/index.html',
      email: 'stmartin.chelsfield@btinternet.com',
      telephone: '+441689825749',
      address: {
        '@type': 'PostalAddress',
        streetAddress: 'Church Road',
        addressLocality: 'Chelsfield, Orpington',
        addressRegion: 'Kent',
        postalCode: 'BR6 7SN',
        addressCountry: 'GB',
      },
    },
  },
  {
    slug: 'about',
    title: 'History &amp; Architecture — St Martin of Tours, Chelsfield',
    description: 'The history of St Martin of Tours, Chelsfield, from its 12th-century origins to the Brass Crosby Rooms extension of 2007.',
    active: 'about.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'visit-us',
    title: 'Visit Us — St Martin of Tours, Chelsfield',
    description: 'How to find St Martin of Tours, Chelsfield: address, map, directions by car, train and on foot, and opening times.',
    active: 'visit-us.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'services',
    title: 'Services — St Martin of Tours, Chelsfield',
    description: 'Our weekly pattern of worship at St Martin of Tours, Chelsfield: Sunday and Wednesday service times.',
    active: 'services.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'calendar',
    title: 'Calendar — St Martin of Tours, Chelsfield',
    description: 'Services and events at St Martin of Tours, Chelsfield, month by month.',
    active: 'calendar.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'get-involved',
    title: 'Groups &amp; Activities — St Martin of Tours, Chelsfield',
    description: 'Groups meeting at St Martin of Tours, Chelsfield — toddler group, choir, bellringers and more — plus how to volunteer or hire the Brass Crosby Rooms.',
    active: 'get-involved.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'people',
    title: 'Clergy &amp; Contacts — St Martin of Tours, Chelsfield',
    description: 'Meet the clergy and officers of St Martin of Tours, Chelsfield.',
    active: 'people.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'newsletter',
    title: 'Newsletter — St Martin of Tours, Chelsfield',
    description: 'Sign up for news, services and events from St Martin of Tours, Chelsfield, straight to your inbox.',
    active: 'newsletter.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'newsletter-archive',
    title: 'Newsletter Archive — St Martin of Tours, Chelsfield',
    description: 'Past newsletter issues from St Martin of Tours, Chelsfield.',
    active: null,
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'privacy-policy',
    title: 'Privacy Policy — St Martin of Tours, Chelsfield',
    description: 'How St Martin of Tours, Chelsfield handles the personal details you give us when signing up for our newsletter.',
    active: null,
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'donate',
    title: 'Donate — St Martin of Tours, Chelsfield',
    description: 'How to support St Martin of Tours, Chelsfield financially.',
    active: null,
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'safeguarding',
    title: 'Safeguarding — St Martin of Tours, Chelsfield',
    description: 'Safeguarding contacts and national helplines for St Martin of Tours, Chelsfield.',
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'contact',
    title: 'Contact — St Martin of Tours, Chelsfield',
    description: 'Get in touch with St Martin of Tours, Chelsfield.',
    active: 'contact.html',
    header: true,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'updates',
    title: 'Site Updates — St Martin of Tours, Chelsfield',
    description: 'Internal build changelog for this site — not linked from anywhere on the site.',
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  // Hidden how-it-works guide for non-technical members of the website
  // team, same pattern as kington-parishes' own help guide: not in
  // NAV/FOOTER_NAV, not pastoral content (no safeguard-strip banner), and
  // noindex/nofollow since it's internal process documentation.
  {
    slug: 'help',
    title: 'Help — How To Update This Website — St Martin of Tours, Chelsfield',
    description: 'A plain-English guide for the website team: how changes reach the live site, and how to set up a laptop to make one.',
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'help-getting-set-up',
    title: 'Setting Up Your Laptop — Help — St Martin of Tours, Chelsfield',
    description: 'How to install Claude Desktop, create a GitHub account, and get set up to make a change to this website.',
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'help-making-a-change',
    title: 'Making a Change — Help — St Martin of Tours, Chelsfield',
    description: 'What happens, step by step, when you ask Claude to update this website.',
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'help-technical-details',
    title: 'Technical Details — Help — St Martin of Tours, Chelsfield',
    description: 'Hosting on Cloudflare Workers, the templated build that keeps the site DRY, what gets tested before a change goes live, and where the source code lives.',
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  {
    slug: 'help-when-it-goes-wrong',
    title: 'When It Goes Wrong — Help — St Martin of Tours, Chelsfield',
    description: 'What to do if a change looks wrong: ask Claude, revert it, or fail forward.',
    active: null,
    header: true,
    safeguardStrip: false,
    robots: 'noindex, nofollow',
  },
  {
    slug: '404',
    title: 'Page not found — St Martin of Tours, Chelsfield',
    description: "This page couldn't be found. Find your way back to the St Martin of Tours home page.",
    active: null,
    header: false,
    safeguardStrip: false,
    canonical: false,
    robots: 'noindex, nofollow',
  },
];
